version: "3"
services:
  db:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "FD0gO0WLh2uBBFuh"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  parser:
    build: "parser"

  